## AUTOML Pycaret

### FINAL TRAIN - cleaned, encoded, standardized (no feature selection)

In [11]:
import pandas as pd
from pycaret.regression import *

In [ ]:
finaltrain = pd.read_csv(r"C:\Users\leila\Downloads\pfaproject\house-price-prediction\data\cleaned data\finaltrain.csv")
finaltrain.drop('Id', axis=1, inplace=True)

In [16]:
setup(data=finaltrain, target='SalePrice', session_id=123)

In [17]:
best_model = compare_models()

In [19]:
data = pd.read_csv(r"C:\Users\leila\Downloads\pfaproject\house-price-prediction\data\cleaned data\finaltest.csv")
data.drop('Id', axis=1, inplace=True)

In [ ]:
model = create_model('gbr') 
tuned_model = tune_model(model)
evaluate_model(tuned_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

### only keep pc1, pc2, all one hot encoded

In [38]:
final = pd.read_csv(r"C:\Users\leila\Downloads\pfaproject\house-price-prediction\data\cleaned data\finaltrain.csv")

In [39]:
# pc1, pc2, one hot encoded
desired_columns = [
    'OverallQual', 'GarageCars', 'GarageArea', 'ExterQual', 'GarageFinish',
    'KitchenQual', 'BsmtQual', 'YearBuilt', 'TotalBsmtSF', 'GrLivArea',
    'TotRmsAbvGrd', '2ndFlrSF', 'BedroomAbvGr', 'BsmtFinType1',
    'BsmtFullBath', 'BsmtFinSF1', 'BsmtUnfSF', 'FullBath', 'KitchenAbvGr', 'SalePrice'
]
one_hot_cols = [
    col for col in final.columns
    if final[col].dropna().isin([True, False]).all()
]

In [40]:
# Combine desired columns with one-hot encoded columns
columns_to_keep = desired_columns + one_hot_cols

# Ensure 'Id' is not in the list
columns_to_keep = [col for col in columns_to_keep if col != 'Id']

# Filter the DataFrame
final_filtered = final[columns_to_keep]

In [41]:
setup(data=final_filtered, target='SalePrice', session_id=123)

In [42]:
best_model1 = compare_models()

In [ ]:
model = create_model('lr')  # 'lr' for Linear Regression